---
title: "Theory of survival analysis using counting processes"
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(ggplot2)
```

## Purpose of the course

The analysis of survival data is critical in medical research, whether one is studying the lifetimes of cells, tumors, or humans. This course aims to develop an intuitive understanding of the theory of survival analysis methods using counting processes and martingales. This will provide participants with a deeper understanding of survival data analysis methods in medical research, enabling them to better interpret and analyze them. 

## Intended learning outcomes

After successfully completing this course, students will be able to:

- Summarize basic asymptotic theory for processes and sketch derivations of basic results involving the empirical cumulative distribution function.
- Identify notation and terminology for counting processes and connect them to survival statistics. 
- Reframe nonparametric estimators of survival quantities in terms of counting processes.
- Paraphrase the martingale central limit theorem and describe how it can be used to perform inference for the Kaplan-Meier estimator.
- Interpret the proportional hazards, additive hazards, and parametric regression models from the counting process perspective. 
- Compare and contrast theoretical and methodological advances in survival analysis, including frailty models, multi-state models, joint models, causal inference and prediction for survival analysis.


## Contents of the course

The course will cover the following topics:

1. Overview of the course. Counting process introduction, notation and terminology.
2. Martingale introduction, terminology, and limit theorems. Censoring, types, assumptions. 
3. Representation of Nelson-Aalen and Kaplan-Meier Estimators. Asymptotic analysis. Logrank tests and variants, Confidence bands.
4. General regression models, likelihood and asymptotic analysis. Time dependent covariates and censoring assumptions.
5. Proportional hazards models, stratified models, residuals. Additive hazards models, relative survival.
6. Non martingale analysis using empirical process theory. Functional delta method and examples.
7. Parametric models, including AFT and flexible parametric, frailty (Andrea Discacciati).
8. Multi state models introduction and regression. Competing risks and illness death models (Therese Andersson).
9. Causal inference, pseudo-observations, multiple time scales, recurrent events.


## Literature

The required course textbook is 

Odd O. Aalen, Ørnulf Borgan and Håkon K. Gjessing. Survival and Event History Analysis: A process point of view. Springer-Verlag, 2008. [ABG]

other required papers will be provided by the teacher. 

Recommended textbooks for further reading are 

Thomas R. Fleming, David P. Harrington. Counting Processes and Survival Analysis. Wiley-New York, 1991.

Per K. Andersen, Ørnulf Borgan, Richard D. Gill, Niels Keiding. Statistical Models Based on Counting Processes. Springer-Verlag, 1993. 



## Contact Information: 

- Michael Sachs (e-mail: michael.sachs@sund.ku.dk), Section of Biostatistics, University of Copenhagen.
