---
title: "Lecture notes and other resources"
---

## Lecture 1 -- Introduction and overview

- [Slides (html)](notes/01-introduction.html)

### Assignment

Read [Breslow and Crowley (1974)](breslow-crowley-1974.pdf), from Section 6 on. Think about how empirical process theory was used here, and why it was needed. 

### Further reading

Van der Vaart, A. W. (2000). Asymptotic statistics (Vol. 3). Cambridge university press.

Shorack, G. R., & Wellner, J. A. (2009). Empirical processes with applications to statistics. Society for Industrial and Applied Mathematics.

## Lecture 2 -- Counting processes in survival analysis

- [Slides (html)](notes/02-counting-intro.html)

### Assignment

Read [Efron (1967)](Efron1967.pdf) and code up a version of the redistribution of mass algorithm in your favorite language. What is the "self-consistency" property and how is it used in Theorem 8.1? 

- Here is one solution: [self-consistency.R](self-consistency.html)

### Further reading

- Chapters 1 and 3 in ABG.
- Chapter 0 in Fleming and Harrington.

## Lecture 3 -- Martingales -- definitions, properties, and applications

- [Slides (html)](notes/03-martingale-intro.html)

### Further reading

- Chapter 2 in ABG.
- Chapter 1 in Fleming and Harrington.

### Assignment

- Complete the derivations of the Poisson process example in the lecture (slides 14 and 20).
- Read Chapter 3 in ABG.
- [Solution (pdf)](poisson-process.pdf)

## Lecture 4 -- Martingale based analysis of nonparametric estimators and tests

- [Slides (html)](notes/04-nonparametrics.html)

### Assignment

- Read Section 3.3 of ABG, paying close scrutiny to section 3.3.5. 
- Start to think about ideas for your presentations (options so far are relative survival, confidence bands, $k$-sample logrank tests)

## Lecture 5 -- Semiparametric Regression Models

- [Slides (html)](notes/05-regression.html)

### Assignment

- Look at section 4.2.3, on martingale tests for the additive model. Can this test be inverted to obtain a confidence band procedure for the cumulative regression functions? 
- Read [Cox (1972)](Cox-1972.pdf)

